# Generated by Django 5.0.3 on 2024-03-09 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('tank', 'Танк'), ('heal', 'Медик'), ('dd', 'Урон'), ('buyers', 'Торговец'), ('gildemaster', 'Гилдмастер'), ('quest', 'Квестгивер'), ('smith', 'Кузнец'), ('tanner', 'Кожевник'), ('potion', 'Зельевар'), ('spellmaster', 'Мастер заклинаний')], default='dd', max_length=32)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
